#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Ansible をインストール、バージョンアップするためのスクリプト
# setup.yml で管理している Ansible は、ここでインストールしたものの設定を管理するのみ。
# バージョンアップする際は、こちらのスクリプトを再実行する必要がある。

# インストールする Ansible のバージョンを設定する
ANSIBLE_VERSION="2.20.0"
PACKAGE_NAME="ansible-core"

# （変更不可）
# Ansible の構成情報を管理するためのディレクトリを定義
ANSIBLE_DIR=$SCRIPT_DIR/ansible

# OS のアップデート
update_os() {
  echo "Updating os ..."
  if ! (sudo apt-get update); then
    echo "Update apt failed."
    exit 1
  fi
}

# Ansible のインストール
ensure_pipx() {
  if ! command -v pipx >/dev/null 2>&1; then
    echo "Installing pipx ..."
    sudo apt-get update
    sudo apt-get install -y pipx
    pipx ensurepath
 fi
}

get_installed_version() {
  if ! pipx list --json >/dev/null 2>&1; then
    echo ""
    return
  fi

  pipx list --short | grep $PACKAGE_NAME | cut -d" " -f 2
}

install_or_update() {
  local current_version
  current_version="$(get_installed_version)"

  if [[ -z "$current_version" ]]; then
    echo "Ansible not installed. Installing $ANSIBLE_VERSION"
    pipx install "$PACKAGE_NAME==$ANSIBLE_VERSION"
  elif [[ "$current_version" == "$ANSIBLE_VERSION" ]]; then
    echo "Ansible $ANSIBLE_VERSION already installed. Nothing to do."
  else
    echo "Updating Ansible from $current_version to $ANSIBLE_VERSION"
    pipx upgrade "$PACKAGE_NAME" --pip-args="==$ANSIBLE_VERSION"
  fi
}

write_version_file() {
  if [[ ! -d $ANSIBLE_DIR ]]; then
    mkdir $ANSIBLE_DIR
  fi

  cat > $ANSIBLE_DIR/ansible_version.yml <<EOF
# This file is auto-generated by manage-ansible.sh
ansible_core_version: "$ANSIBLE_VERSION"
EOF
}

stow_configuration_files() {
  if [[ ! -d $CONF_DIR ]]; then
    echo "$CONF_DIR was not found."
    exit 1
  fi

  for d in $(find $CONF_DIR -maxdepth 1 -type d | cut -d"/" -f 2 | grep -v '^\.'); do
    stow -R -t $HOME $CONF_DIR/$d
  done
}

main() {
  update_os
  ensure_pipx
  install_or_update
  write_version_file
  echo "Done."
}

main "$@"

