[tools]
starship = "latest"
bat = "latest"
eza = "latest"
rg = "latest"
fzf = "latest"
fd = "latest"
yazi = "latest"
zoxide = "latest"

neovim = "latest"

github-cli = "latest"
lazygit = "latest"
jq = "latest"
zellij = "latest"
codex = "latest"
ast-grep = "latest"
tree-sitter = "latest"
node = "24"
npm = "11"
"aqua:dlvhdr/diffnav" = "latest"
delta = "latest"

[shell_alias]
ls = "eza"
cat = "bat"
grep = "rg"
y = "yazi"
z = "zoxide"
lg = "lazygit"
catp = "bat --plain"
vi = "nvim"
