# 設定に必要な基礎情報を初回に入力させ、local.yml に記録する
# 再設定する場合は local.yml を消すか直接編集する必要がある
- name: local.yml 存在確認
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/vars/local.yml"
  register: local_file

- name: user.name を入力
  ansible.builtin.pause:
    prompt: "user.name を入力してください（Git, GPGに利用）"
  register: input_name
  when: not local_file.stat.exists

- name: user.email を入力
  ansible.builtin.pause:
    prompt: "user.email を入力してください（Git, GPGに利用）"
  register: input_email
  when: not local_file.stat.exists

- name: local.yml 作成
  ansible.builtin.copy:
    dest: "{{ playbook_dir }}/vars/local.yml"
    content: |
      user_name: "{{ input_name.user_input }}"
      user_email: "{{ input_email.user_input }}"
    mode: '0600'
  when: not local_file.stat.exists

- name: local.yml 読み込み
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/vars/local.yml"

