- name: git user.name 設定
  ansible.builtin.command:
    cmd: git config --global user.name "{{ user_name }}"
  changed_when: false

- name: git user.email 設定
  ansible.builtin.command:
    cmd: git config --global user.email "{{ user_email }}"
  changed_when: false

- name: git defaultBranch name 設定
  ansible.builtin.command:
    cmd: git config --global init.defaultBranch main
  changed_when: false

